# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1400, 950)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.View = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.View.sizePolicy().hasHeightForWidth())
        self.View.setSizePolicy(sizePolicy)
        self.View.setMinimumSize(QtCore.QSize(1000, 0))
        self.View.setMaximumSize(QtCore.QSize(1920, 1080))
        self.View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.View.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.View.setObjectName("View")
        self.gridLayout.addWidget(self.View, 0, 4, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.newCal_rb = QtWidgets.QRadioButton(self.groupBox_4)
        self.newCal_rb.setChecked(True)
        self.newCal_rb.setObjectName("newCal_rb")
        self.verticalLayout_3.addWidget(self.newCal_rb)
        self.oldCal_rb = QtWidgets.QRadioButton(self.groupBox_4)
        self.oldCal_rb.setObjectName("oldCal_rb")
        self.verticalLayout_3.addWidget(self.oldCal_rb)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.nmbViews1 = QtWidgets.QSpinBox(self.groupBox)
        self.nmbViews1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.nmbViews1.setMinimum(0)
        self.nmbViews1.setProperty("value", 0)
        self.nmbViews1.setObjectName("nmbViews1")
        self.verticalLayout_6.addWidget(self.nmbViews1)
        self.addPointFile_b = QtWidgets.QPushButton(self.groupBox)
        self.addPointFile_b.setEnabled(False)
        self.addPointFile_b.setObjectName("addPointFile_b")
        self.verticalLayout_6.addWidget(self.addPointFile_b)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_8.setEnabled(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.nmbViews2 = QtWidgets.QSpinBox(self.groupBox_8)
        self.nmbViews2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.nmbViews2.setMinimum(0)
        self.nmbViews2.setProperty("value", 0)
        self.nmbViews2.setObjectName("nmbViews2")
        self.verticalLayout_7.addWidget(self.nmbViews2)
        self.loadFilledTable_b = QtWidgets.QPushButton(self.groupBox_8)
        self.loadFilledTable_b.setEnabled(False)
        self.loadFilledTable_b.setObjectName("loadFilledTable_b")
        self.verticalLayout_7.addWidget(self.loadFilledTable_b)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newView_b = QtWidgets.QPushButton(self.groupBox_2)
        self.newView_b.setMaximumSize(QtCore.QSize(150, 100))
        self.newView_b.setObjectName("newView_b")
        self.verticalLayout_2.addWidget(self.newView_b)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.view_lw = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_lw.sizePolicy().hasHeightForWidth())
        self.view_lw.setSizePolicy(sizePolicy)
        self.view_lw.setMaximumSize(QtCore.QSize(500, 16777215))
        self.view_lw.setObjectName("view_lw")
        self.verticalLayout_2.addWidget(self.view_lw)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.slider = QtWidgets.QSlider(self.groupBox_2)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.verticalLayout_2.addWidget(self.slider)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setEnabled(False)
        self.groupBox_6.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lowContour_le = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowContour_le.sizePolicy().hasHeightForWidth())
        self.lowContour_le.setSizePolicy(sizePolicy)
        self.lowContour_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lowContour_le.setObjectName("lowContour_le")
        self.gridLayout_2.addWidget(self.lowContour_le, 3, 1, 1, 1)
        self.binary_le = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binary_le.sizePolicy().hasHeightForWidth())
        self.binary_le.setSizePolicy(sizePolicy)
        self.binary_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.binary_le.setObjectName("binary_le")
        self.gridLayout_2.addWidget(self.binary_le, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 2, 1, 1)
        self.binary_b = QtWidgets.QPushButton(self.groupBox_6)
        self.binary_b.setObjectName("binary_b")
        self.gridLayout_2.addWidget(self.binary_b, 5, 0, 1, 1)
        self.contour_lw = QtWidgets.QListWidget(self.groupBox_6)
        self.contour_lw.setObjectName("contour_lw")
        self.gridLayout_2.addWidget(self.contour_lw, 1, 0, 3, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 2, 1, 1)
        self.upContour_le = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upContour_le.sizePolicy().hasHeightForWidth())
        self.upContour_le.setSizePolicy(sizePolicy)
        self.upContour_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.upContour_le.setObjectName("upContour_le")
        self.gridLayout_2.addWidget(self.upContour_le, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 2, 1, 1)
        self.correct_b = QtWidgets.QPushButton(self.groupBox_6)
        self.correct_b.setObjectName("correct_b")
        self.gridLayout_2.addWidget(self.correct_b, 5, 1, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 6, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.calibrate_b = QtWidgets.QPushButton(self.groupBox_5)
        self.calibrate_b.setObjectName("calibrate_b")
        self.verticalLayout_5.addWidget(self.calibrate_b)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 2, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tableWidget)
        self.saveTable_b = QtWidgets.QPushButton(self.tab)
        self.saveTable_b.setEnabled(True)
        self.saveTable_b.setObjectName("saveTable_b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.saveTable_b)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadCal_b = QtWidgets.QPushButton(self.groupBox_3)
        self.loadCal_b.setEnabled(False)
        self.loadCal_b.setObjectName("loadCal_b")
        self.verticalLayout.addWidget(self.loadCal_b)
        self.loadTest_b = QtWidgets.QPushButton(self.groupBox_3)
        self.loadTest_b.setObjectName("loadTest_b")
        self.verticalLayout.addWidget(self.loadTest_b)
        self.testCal_b = QtWidgets.QPushButton(self.groupBox_3)
        self.testCal_b.setObjectName("testCal_b")
        self.verticalLayout.addWidget(self.testCal_b)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.pointsTested_l = QtWidgets.QLabel(self.groupBox_7)
        self.pointsTested_l.setObjectName("pointsTested_l")
        self.gridLayout_5.addWidget(self.pointsTested_l, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBox_7)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 0, 1, 1)
        self.xmean_l = QtWidgets.QLabel(self.frame)
        self.xmean_l.setObjectName("xmean_l")
        self.gridLayout_4.addWidget(self.xmean_l, 1, 1, 1, 1)
        self.ymean_l = QtWidgets.QLabel(self.frame)
        self.ymean_l.setObjectName("ymean_l")
        self.gridLayout_4.addWidget(self.ymean_l, 2, 1, 1, 1)
        self.zmean_l = QtWidgets.QLabel(self.frame)
        self.zmean_l.setObjectName("zmean_l")
        self.gridLayout_4.addWidget(self.zmean_l, 3, 1, 1, 1)
        self.xstd_l = QtWidgets.QLabel(self.frame)
        self.xstd_l.setObjectName("xstd_l")
        self.gridLayout_4.addWidget(self.xstd_l, 1, 2, 1, 1)
        self.ystd_l = QtWidgets.QLabel(self.frame)
        self.ystd_l.setObjectName("ystd_l")
        self.gridLayout_4.addWidget(self.ystd_l, 2, 2, 1, 1)
        self.zstd_l = QtWidgets.QLabel(self.frame)
        self.zstd_l.setObjectName("zstd_l")
        self.gridLayout_4.addWidget(self.zstd_l, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 2, 0, 1, 2)
        self.saveTest_b = QtWidgets.QPushButton(self.groupBox_7)
        self.saveTest_b.setObjectName("saveTest_b")
        self.gridLayout_5.addWidget(self.saveTest_b, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.test_tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.test_tableWidget.setObjectName("test_tableWidget")
        self.test_tableWidget.setColumnCount(0)
        self.test_tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.test_tableWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.newCal_rb.toggled['bool'].connect(self.groupBox.setEnabled)
        self.oldCal_rb.toggled['bool'].connect(self.groupBox_8.setEnabled)
        self.nmbViews1.valueChanged['int'].connect(self.addPointFile_b.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Step 1: Calibration setup:"))
        self.newCal_rb.setText(_translate("MainWindow", "Populate a new calibration table"))
        self.oldCal_rb.setText(_translate("MainWindow", "Import a previously populated calibration table"))
        self.groupBox.setTitle(_translate("MainWindow", "New calibration table:"))
        self.label_11.setText(_translate("MainWindow", "Specify # of views:"))
        self.nmbViews1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose the number of views you wish to load of your calibration object(s). A minimum of 2 views is required. In many cases, a view will be a still frame image taken of the calibration object from one of two, or three, syncronized cameras (they can be syncronized by sharing a master image clock). Alternatively, carefully placed mirrors and only one camera can be used to attain simultaneous views of the object. When using mirrors, one needs to seperate each view into a separate image file prior to uploading into the software.</p></body></html>"))
        self.addPointFile_b.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load a .csv file containing the x y and z data (in seperate columns). Each row in the file corresponds to a real-world position of a calibration marker visible in each view. The first row is therefore for the calibration marker 1, the second row for the calibration marker 2, etc...</p></body></html>"))
        self.addPointFile_b.setText(_translate("MainWindow", "Import xyz point file"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Import populated calibration table:"))
        self.label_9.setText(_translate("MainWindow", "Specify # of views:"))
        self.loadFilledTable_b.setToolTip(_translate("MainWindow", "Loads data saved from a previously populated table. The points will appear on their respective view."))
        self.loadFilledTable_b.setText(_translate("MainWindow", "Load previously populated xyz point file"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Step 2: Place calibration markers on views"))
        self.newView_b.setText(_translate("MainWindow", "Add  a view"))
        self.label_2.setText(_translate("MainWindow", "Select view to place markers on:"))
        self.label.setText(_translate("MainWindow", "Zoom in on active view:"))
        self.pushButton_3.setText(_translate("MainWindow", "Continue"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Step 3: Improve centroid detection:"))
        self.lowContour_le.setText(_translate("MainWindow", "50"))
        self.binary_le.setText(_translate("MainWindow", "50"))
        self.label_14.setText(_translate("MainWindow", "min. contour area"))
        self.binary_b.setText(_translate("MainWindow", "Redo binarization"))
        self.label_12.setText(_translate("MainWindow", "max. contour area"))
        self.upContour_le.setText(_translate("MainWindow", "1000"))
        self.label_17.setText(_translate("MainWindow", "Select a contour:"))
        self.label_13.setText(_translate("MainWindow", "binary threshold"))
        self.correct_b.setToolTip(_translate("MainWindow", "<html><head/><body><p>Aligns the centers of the manually placed points to the centroids of the detected calibration markers (red dot in the _ctrs image). This is done using a computer vision algorithm. Dots that have correctly \'snapped\' to the centroid of the calirbation marker will change color from red to green. If a dot remains red, it is <span style=\" font-weight:600; font-style:italic;\">very </span>likely because the contrast between the calibration marker and its immediate surroundings is not strong enough. To remedy this problem, additional pre-processing of the image is required in a program such as Gimp to improve the contrast and hence the detectability of the point. If a green dot looks \'off\' of center, it is also likely due to poor contrast casuing an incorrect detection of the center of the calibration marker. </p></body></html>"))
        self.correct_b.setText(_translate("MainWindow", "Correct marker centers"))
        self.pushButton_4.setText(_translate("MainWindow", "Continue"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Step 4: Perform 3D calibration"))
        self.calibrate_b.setToolTip(_translate("MainWindow", "<html><head/><body><p>Performs the 3D calibration. A fully populated table containing a minimum of 2 views each containing a minimum of 8 points is required.</p></body></html>"))
        self.calibrate_b.setText(_translate("MainWindow", "Calibrate 3D"))
        self.saveTable_b.setToolTip(_translate("MainWindow", "Saves the table\'s data to file for later use."))
        self.saveTable_b.setText(_translate("MainWindow", "Save table to file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Table view"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Test controls:"))
        self.loadCal_b.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load in an older calibration file. If no file is selected, the last calibration performed will be used when \'Test 3D calibration\' is clicked. </p></body></html>"))
        self.loadCal_b.setText(_translate("MainWindow", "Load calibration"))
        self.loadTest_b.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load in an *.csv file including the real-world coordinates of any number of detectable objects appearing in each of the views used to perform the 3D calibration. The format of this file is identical to the file format used when the \'Table view\' data is saved to file (i.e. each row contains x,y,z followed by the x and y pixel coordinates for each view).  </p></body></html>"))
        self.loadTest_b.setText(_translate("MainWindow", "Load test points"))
        self.testCal_b.setText(_translate("MainWindow", "Test 3D calibration"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Test statistics:"))
        self.label_6.setText(_translate("MainWindow", "number of points tested:"))
        self.pointsTested_l.setText(_translate("MainWindow", "0"))
        self.xmean_l.setText(_translate("MainWindow", "0"))
        self.ymean_l.setText(_translate("MainWindow", "0"))
        self.zmean_l.setText(_translate("MainWindow", "0"))
        self.xstd_l.setText(_translate("MainWindow", "0"))
        self.ystd_l.setText(_translate("MainWindow", "0"))
        self.zstd_l.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "std. of error:"))
        self.label_8.setText(_translate("MainWindow", "mean error:"))
        self.label_5.setText(_translate("MainWindow", "z"))
        self.label_4.setText(_translate("MainWindow", "y"))
        self.label_3.setText(_translate("MainWindow", "x"))
        self.saveTest_b.setText(_translate("MainWindow", "Save test results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Test 3D calibration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

